version: '3'
services:
  mongodb:
    image: mongo:4.2.3-bionic
    container_name: mongodb
    ports:
        - 27017:27017
    environment:
        - MONGO_INITDB_DATABASE=test
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=admin
        - MONGO_INITDB_DATABASE:test
    volumes: 
        - ./mongodb-init.js:/docker-entrypoint-initdb.d/mongodb-init.js:ro
        - ./mongodb:/data/db
        - ./mongoconfig:/data/configdb
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@test:27017/
        
